8290889: JDK 19 RDP2 L10n resource files update - msgdrop 10
openjdk/jdk19 pull request #154
Opened 2022-07-23 03:03 UTC by alisenchung

open l10n msg drop
All tests passed.

2022-07-25 17:02 UTC, naotoj requested changes

2022-07-25 18:48 UTC, alexeysemenyukoracle reviewed
Why `MSG_Help_mac_launcher` in [src/jdk.jpackage/share/classes/jdk/jpackage/internal/resources/HelpResources_de.properties](https://github.com/openjdk/jdk19/pull/154/files#diff-2e1b121e201e1040827d5b68ebdd852615e611904db783806a753dc6980e97fa) is left not localized? Is it intended to be localized in the next drop?

2022-07-26 18:29 UTC, alisenchung commented
> Why `MSG_Help_mac_launcher` in [src/jdk.jpackage/share/classes/jdk/jpackage/internal/resources/HelpResources_de.properties](https://github.com/openjdk/jdk19/pull/154/files#diff-2e1b121e201e1040827d5b68ebdd852615e611904db783806a753dc6980e97fa) is left not localized? Is it intended to be localized in the next drop?

Probably will be left for next drop

2022-07-28 20:51 UTC, naotoj requested changes
- src/jdk.localedata/share/classes/sun/util/resources/ext/CurrencyNames_en_US.properties: this should not be moved from `java.base` module
- I still need some comments explaining `XXX=XXX` in the root bundle of `CurrencyNames`. Something like 
```
These currency symbol entries are for the root bundle only to avoid throwing a MissingResourceException. Should not be copied into each localized resource bundle.
```

2022-07-28 20:51 UTC, naotoj commented on src/jdk.localedata/share/classes/sun/util/resources/ext/CurrencyNames_zh_CN.properties
> -CNY=\uffe5
Do not remove the original translation.

2022-08-01 16:43 UTC, naotoj approved these changes
LGTM

2022-08-09 17:42 UTC, alexeysemenyukoracle approved these changes

2022-08-09 17:42 UTC, alexeysemenyukoracle commented
jpackage changes look good. Approved that part.

2022-08-09 20:29 UTC, alisenchung commented
/integrate

2022-08-09 22:25 UTC, alexeysemenyukoracle commented
/sponsor

2022-08-09 22:28 UTC, closed without merging