8288759: GCC 12 fails to compile signature.cpp due to -Wstringop-overread bug
openjdk/jdk19 pull request #49
Opened 2022-06-20 17:58 UTC by shipilev

Trying to compile with GCC 12.1.1 (current Fedora Rawhide) yields this failure:

```
In file included from /home/test/shipilev-jdk/src/hotspot/share/utilities/globalDefinitions_gcc.hpp:35,
                 from /home/test/shipilev-jdk/src/hotspot/share/utilities/globalDefinitions.hpp:35,
                 from /home/test/shipilev-jdk/src/hotspot/share/memory/allocation.hpp:29,
                 from /home/test/shipilev-jdk/src/hotspot/share/classfile/classLoaderData.hpp:28,
                 from /home/test/shipilev-jdk/src/hotspot/share/precompiled/precompiled.hpp:34:
In function 'const void* memchr(const void*, int, size_t)',
    inlined from 'int SignatureStream::scan_type(BasicType)' at /home/test/shipilev-jdk/src/hotspot/share/runtime/signature.cpp:343:32,
    inlined from 'void SignatureStream::next()' at /home/test/shipilev-jdk/src/hotspot/share/runtime/signature.cpp:373:19,
    inlined from 'void SignatureIterator::do_parameters_on(T*) [with T = Fingerprinter]' at /home/test/shipilev-jdk/src/hotspot/share/runtime/signature.hpp:635:41,
    inlined from 'void SignatureIterator::do_parameters_on(T*) [with T = Fingerprinter]' at /home/test/shipilev-jdk/src/hotspot/share/runtime/signature.hpp:629:6,
    inlined from 'void Fingerprinter::compute_fingerprint_and_return_type(bool)' at /home/test/shipilev-jdk/src/hotspot/share/runtime/signature.cpp:169:19:
/usr/include/string.h:102:27: error: 'void* __builtin_memchr(const void*, int, long unsigned int)' specified bound [18446744073709486082, 0] exceeds maximum object size 9223372036854775807 [-Werror=stringop-overread]
  102 |   return __builtin_memchr (__s, __c, __n);
      |          ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

I believe this is actually a GCC false warning:
  https://bugzilla.redhat.com/show_bug.cgi?id=2075786

We can disable this warning at a particular site, though, hoping that other prospective warnings would not be false.

(In this PR, I also moved the recently added block for other warning in more chronological order)

Additional testing:
 - [x] Linux x86_64 fastdebug build with GCC 12.1.1
 - [x] Linux x86_64 fastdebug build with GCC 9.4.0

2022-06-22 16:28 UTC, shipilev commented
Any takers? :)

2022-06-23 21:25 UTC, coleenp approved these changes
Seems fine.

2022-06-25 08:37 UTC, kimbarrett requested changes

2022-06-25 08:37 UTC, kimbarrett commented on src/hotspot/share/utilities/compilerWarnings_gcc.hpp
> +#endif
But note this part of the change shouldn't be done at all, per my comments elsewhere.

2022-06-25 08:37 UTC, kimbarrett commented on src/hotspot/share/runtime/signature.cpp
> +PRAGMA_STRINGOP_OVERREAD_IGNORED
Don't make this change.  The warning is indicating an actual problem with the code.  The while loop on line 338 may terminate with `end == limit` if the string consists of just a sequence of '[' and then ends.  If the loop ends for that reason, we later read `base[limit]`, invoking UB as limit is the length of base.  As a proof of concept, adding
```
if (end >= limit) return limit;
```
after the while loop makes the warning go away.  I have no idea what the correct thing to do for this might be.  Returning limit might be wrong; I just used that to verify this issue is the source of the warning.

2022-07-04 11:48 UTC, shipilev commented on src/hotspot/share/runtime/signature.cpp
> +PRAGMA_STRINGOP_OVERREAD_IGNORED
You're right, this is a legit warning. I see other code in `signature.cpp` that handles `JVM_SIGNATURE_ARRAY` scans and checks whether we ended up scanning the string completely. We should do the same here. Let me see...

2022-07-04 12:38 UTC, shipilev commented
@kimbarrett, @coleenp -- I redid the fix to fix the actual warning instead. I opted to return `limit` on the failure path + assert it does not actually happen in practice. It looks that returning `limit` is acceptable, as it rolls over to the "end of signature" on error. We can make that `fatal()` instead, but I don't like to penalize `release` builds unnecessarily.

2022-07-05 01:06 UTC, kimbarrett reviewed
The proposed fix seems plausible, and addresses the warning.  I was a little worried that someone might come along later and try to change it to just
```
assert(end < limit, "invalid type");
```
but presumably that will get the warning again during testing.

I tried to think of a less contrived way to write this while still addressing the warning.  I haven't come up with anything better, assuming returning limit is okay.

But I'm entirely unfamiliar with the signature code, so don't know if returning limit is okay.  So don't count me as a reviewer for this change (and I won't hit the Approve button).

2022-08-02 08:22 UTC, shipilev commented
Closed in favor of https://github.com/openjdk/jdk/pull/9711

2022-08-02 08:22 UTC, closed without merging